import importlib
import importlib.metadata
import click
import logging

# Default logging level - will be changed if --debug is passed
logging.basicConfig(level=logging.WARNING, format='%(levelname)s:%(name)s:%(message)s')


def _build_unavailable_command(command_name, error):
    @click.command(
        name=command_name,
        context_settings={
            'help_option_names': ['-h', '--help'],
            'ignore_unknown_options': True,
            'allow_extra_args': True,
        },
    )
    @click.pass_context
    def unavailable_command(ctx):
        hint = ""
        if "_ctypes" in str(error):
            hint = " Python runtime is missing '_ctypes' (usually missing libffi during Python build)."
        raise click.ClickException(
            f"Module '{command_name}' is unavailable: {error}.{hint}"
        )

    return unavailable_command


class LazyGroup(click.Group):
    def __init__(self, *args, lazy_subcommands=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.lazy_subcommands = lazy_subcommands or {}

    def list_commands(self, ctx):
        commands = set(super().list_commands(ctx))
        commands.update(self.lazy_subcommands.keys())
        return sorted(commands)

    def get_command(self, ctx, cmd_name):
        command = super().get_command(ctx, cmd_name)
        if command is not None:
            return command

        target = self.lazy_subcommands.get(cmd_name)
        if not target:
            return None

        module_name, attribute_name = target.split(":", 1)
        try:
            module = importlib.import_module(module_name)
            command = getattr(module, attribute_name)
        except Exception as exc:
            return _build_unavailable_command(cmd_name, exc)

        self.add_command(command, cmd_name)
        return command


@click.group(
    cls=LazyGroup,
    lazy_subcommands={
        "config": "pyadm.config_commands:config_cli",
        "elastic": "pyadm.elastic.click_commands:elastic",
        "ldap": "pyadm.ldapcli.click_commands:ldapcli",
        "pve": "pyadm.pvecli.pve_commands:pvecli",
    },
    context_settings={'help_option_names': ['-h', '--help']},
)
@click.option('--debug', is_flag=True, help='Enable debug logging')
def cli(debug):
    """pyadm - Swiss Army Knife for Engineers and Administrators

    This tool provides modular functionality to perform various tasks efficiently.
    Currently, the available modules are 'ldap', 'elastic', and 'pve'.

    Usage: pyadm <module> SUBCOMMAND [OPTIONS]

    For more information on a particular subcommand, run 'pyadm <module> SUBCOMMAND --help'.

    \b
    Examples:
        pyadm ldap user jdoe             # Retrieve information for a user in the LDAP directory
        pyadm ldap groups jdoe           # Show groups associated with a user in the LDAP directory
        pyadm ldap members "Developers"  # Show members of a group in the LDAP directory
        pyadm elastic indices            # List all indices in the elastic cluster
        pyadm pve vm list                # List all VMs on Proxmox VE
        pyadm pve ct start mycontainer   # Start a container by name
    """
    # Configure logging level based on debug flag
    if debug:
        logging.getLogger().setLevel(logging.DEBUG)
        logging.debug("Debug logging enabled")

@click.command()
def version():
    """Display version information."""
    try:
        installed_version = importlib.metadata.version("pyadm-toolkit")
    except importlib.metadata.PackageNotFoundError:
        # Running from a source checkout that was never installed.
        installed_version = "unknown (not installed)"
    click.echo(f"Version: {installed_version}")


@click.command(context_settings={'help_option_names': ['-h', '--help']})
@click.argument('shell', type=click.Choice(['bash', 'zsh', 'fish']), required=True)
def completion(shell):
    """Show how to enable shell completion for pyadm.

    SHELL: The shell to set completion up for (bash, zsh, fish)

    Completion is generated by Click from the actual command tree, so it always
    covers every command and option, including ones added after you set it up.

    \b
    BASH:
        echo 'eval "$(_PYADM_COMPLETE=bash_source pyadm)"' >> ~/.bashrc

    \b
    ZSH:
        echo 'eval "$(_PYADM_COMPLETE=zsh_source pyadm)"' >> ~/.zshrc

    \b
    FISH:
        _PYADM_COMPLETE=fish_source pyadm > ~/.config/fish/completions/pyadm.fish
    """
    instructions = {
        'bash': (
            'eval "$(_PYADM_COMPLETE=bash_source pyadm)"',
            "Add the line above to ~/.bashrc to make it permanent.",
        ),
        'zsh': (
            'eval "$(_PYADM_COMPLETE=zsh_source pyadm)"',
            "Add the line above to ~/.zshrc to make it permanent.",
        ),
        'fish': (
            '_PYADM_COMPLETE=fish_source pyadm > ~/.config/fish/completions/pyadm.fish',
            "Run the line above once; fish picks the file up on the next start.",
        ),
    }
    command, hint = instructions[shell]
    click.echo(command)
    click.echo(f"# {hint}")


# Register built-in commands
cli.add_command(version)
cli.add_command(completion)



if __name__ == "__main__":
    cli()
